### ISSUE TITLE
Terms Tool documentation missing screenshots

### ISSUE THREAD

**Issue by techsvcslib** [coral-erm/documentation#21]
I was researching the documentation for the Terms Tool and noticed that there seems to be some missing pieces (e.g. screenshots):

http://docs.coral-erm.org/en/latest/terms.html

For example, the second paragraph mentions a screenshot but there isn't one where it's referred to:

"The process of using the Terms Tool begins with the license record within CORAL Licensing. The first step is for the licensing personnel to create a license record with completed expressions as in the following screenshot."

**Comment by scottvieira** [comment]
Would you check out the following and let me know if this will work?  If so, I will close this issue.

http://docs.coral-erm.org/en/latest/terms.html?highlight=terms

**Comment by techsvcslib** [comment]
It looks ok to me except there is a broken image link still. See attached screenshot. Also, I'm working on testing the terms tool functionality in our local test instance to verify everything and haven't gotten that in place just yet.
![2017-12-10_11-12-08](https://user-images.githubusercontent.com/3106487/33807366-50c817ea-dd9b-11e7-9454-f1b7e517884d.gif)

**Comment by xsong9** [comment]
@techsvcslib @scottvieira I fixed the image showing issue. Github is very picky about capitalization in the file extension.

**Comment by xsong9** [comment]
See the update on this link. 
http://docs.coral-erm.org/en/latest/terms.html
