### ISSUE TITLE
Installation Software Requirements section needs more info

### ISSUE THREAD

**Issue by t4k** [coral-erm/documentation#28]
https://github.com/coral-erm/documentation/blob/master/source/install.md#software-requirements

I think it would be very helpful, and reduce the number of inquiries to help and the mailing list if a few items are added to the software requirements.

- for PHP 5 the system needs the MySQL Native Driver extension (mysqlnd)
- for all versions(?) of PHP the Multibyte String extension is required (mbstring)
- the server needs to have software for sending mail like sendmail or postfix

**Comment by scottvieira** [comment]
@t4k Sounds good.  Do you want to add it and submit a PR for it?  If not, just let me know and I will add it.

**Comment by t4k** [comment]
I don’t have time to do it right now; I just wanted to make sure I recorded this and got it out of my head.

**Comment by scottvieira** [comment]
@tk4 If I add these notes to the documentation next week, do I need to flesh them out some more or are they good to go as written?

**Comment by veggiematts** [comment]
mysqlnd and mbstring have been added.
