### ISSUE TITLE
Link to CORAL schema

### ISSUE THREAD

**Issue by techsvcslib** [coral-erm/documentation#29]
I don't think a link to the CORAL schema is anywhere: http://www.coral-erm.org/schema/

**Comment by scottvieira** [comment]
@techsvcslib I added a link to it in the technical documentation.  http://docs.coral-erm.org/en/latest/technical.html#database-schema

I'm not sure if this is the only place to put it.  I thought about adding a link to it on the Documentation webpage, but it seemed somewhat misplaced there next to the CORAL Community Documentation and SirsiDynix's documentation.
